### ISSUE TITLE
the unary `!` operator causes the compiler to crash

### ISSUE THREAD

**Issue by MinekPo1** [UMRnInside/MlogEvo#4]
I would try to figure out why but its half till 1 am and I'm tired.

Error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/lily/.local/lib/python3.11/site-packages/mlogevo/__main__.py", line 119, in <module>
    main()
  File "/home/lily/.local/lib/python3.11/site-packages/mlogevo/__main__.py", line 110, in main
    result = backend.compile(frontend_result, dump_blocks=args.print_basic_blocks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lily/.local/lib/python3.11/site-packages/mlogevo/backend/backend.py", line 57, in compile
    read_variable_types(function.instructions, variable_types)
  File "/home/lily/.local/lib/python3.11/site-packages/mlogevo/backend/backend.py", line 31, in read_variable_types
    if ir.dest == "" or ir.instruction.startswith("__"):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeDecl' object has no attribute 'startswith'
```

Example code:

```c
void main () {
	int a = !0;
}
```

enjoy debugging.

**Comment by UMRnInside** [comment]
https://github.com/UMRnInside/MlogEvo/blob/f5c5cb485c6f179537c3348c89a5a064f88f2af3/mlogevo/frontend/compiler_sketch.py#LL374C42-L374C42

Sorry, I made a typo there. My fault :(

**Comment by UMRnInside** [comment]
https://github.com/UMRnInside/MlogEvo/commit/df3390b4e43b4bef8acd1d8b3d67b5106043bab2

Done. Try upgrading MlogEvo with `pip install -U git+https://github.com/UMRnInside/mlogevo`

**Comment by MinekPo1** [comment]
No worries, happens to everyone!

**Comment by MinekPo1** [comment]
Can confirm, works. Can be closed.
